
version: '3.8'
services:
  wings:
    image: ghcr.io/pterodactyl/wings:v1.11.8
    restart: always
    networks:
      - wings_network
    ports:
      - "8080:8080"
      - "2022:2022"
    tty: true
    environment:
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - /etc/pterodactyl/:/etc/pterodactyl/
      - /var/lib/pterodactyl/:/var/lib/pterodactyl/
      - /var/log/pterodactyl/:/var/log/pterodactyl/
      - /tmp/pterodactyl/:/tmp/pterodactyl/
      - /etc/ssl/certs:/etc/ssl/certs:ro
networks:
  wings_network:
    name: wings_network
    driver: bridge
