
"use client";

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import type { Node } from '@/lib/types';
import { Button } from '../ui/button';
import { useToast } from '@/hooks/use-toast';

const mockConfig = (node: Node) => `# Mock config.yml for ${node.name}
# In a real app, this would be generated by the backend.
debug: false
uuid: ${node.uuid}
token_id: ${node.tokenId}
token: ${node.token}
api:
  host: 0.0.0.0
  port: ${node.daemonPort}
  ssl:
    enabled: ${node.useSSL}
    cert: /etc/letsencrypt/live/your.domain/fullchain.pem
    key: /etc/letsencrypt/live/your.domain/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://localhost:3000' # Replace with your panel's URL
`;


export function NodeConfiguration({ node }: { node: Node }) {
  const [config] = useState<string>(mockConfig(node));
  const { toast } = useToast();

  const copyToClipboard = () => {
    if (config) {
        navigator.clipboard.writeText(config).then(() => {
            toast({
                title: "Copied to Clipboard",
                description: "The configuration has been copied.",
            });
        }, (err) => {
            toast({
                title: "Failed to Copy",
                description: "Could not copy the configuration to your clipboard.",
                variant: "destructive"
            });
        });
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Configuration File</CardTitle>
        <CardDescription>
            This YAML configuration is dynamically generated for your node.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="relative">
            <pre className="text-sm font-mono whitespace-pre-wrap bg-muted rounded-md border p-4 text-foreground overflow-x-auto max-h-[400px]">
                <code>{config}</code>
            </pre>
            <Button 
                variant="ghost" 
                size="sm" 
                className="absolute top-2 right-2"
                onClick={copyToClipboard}
            >
                Copy
            </Button>
        </div>
        <p className="text-sm text-muted-foreground">
            Place this in your daemon's root directory (e.g., <code className="bg-muted p-1 rounded-sm">/etc/pterodactyl</code>) in a file named <code className="bg-muted p-1 rounded-sm">config.yml</code>.
        </p>
      </CardContent>
    </Card>
  );
}
